# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            A Maze of Maize
url:              http://christine-xu.github.io
paginate:         5
baseurl:          /
author:
  name:           Christine Xu
  url:            http://christine-xu.github.io

# Custom vars
version:          1.0.0
github:
  repo:           
